##########################################################################################
# OVERHEAD PANEL LABELS
##########################################################################################

from aircraft.A319.controls import AirbusLabel
from lib.controls import DynamicLabel

# AirbusFBW/OHPLightsATA21[64]
overhead_panel_labels = [
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA21",
        "xplane_dref_index": 0,
        "touchosc_address": "/label/air_cond_eng_1_bleed_lower",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA21",
        "xplane_dref_index": 1,
        "touchosc_address": "/label/air_cond_eng_1_bleed_upper",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA21",
        "xplane_dref_index": 2,
        "touchosc_address": "/label/air_cond_eng_2_bleed_lower",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA21",
        "xplane_dref_index": 3,
        "touchosc_address": "/label/air_cond_eng_2_bleed_upper",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA21",
        "xplane_dref_index": 4,
        "touchosc_address": "/label/air_cond_apu_bleed_lower",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA21",
        "xplane_dref_index": 5,
        "touchosc_address": "/label/air_cond_apu_bleed_upper",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA21",
        "xplane_dref_index": 6,
        "touchosc_address": "/label/air_cond_pack_1_lower",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA21",
        "xplane_dref_index": 7,
        "touchosc_address": "/label/air_cond_pack_1_upper",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA21",
        "xplane_dref_index": 8,
        "touchosc_address": "/label/air_cond_pack_2_lower",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA21",
        "xplane_dref_index": 9,
        "touchosc_address": "/label/air_cond_pack_2_upper",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA21",
        "xplane_dref_index": 10,
        "touchosc_address": "/label/air_cond_hot_air_lower",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA21",
        "xplane_dref_index": 11,
        "touchosc_address": "/label/air_cond_hot_air_upper",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA21",
        "xplane_dref_index": 12,
        "touchosc_address": "/label/air_cond_ram_air",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA21",
        "xplane_dref_index": 13,
        "touchosc_address": "/label/cabin_press_ditching",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA21",
        "xplane_dref_index": 14,
        "touchosc_address": "/label/cabin_press_mode_sel",
    },
    # {"control_type": AirbusLabel, "xplane_dref_address": "AirbusFBW/OHPLightsATA21", "xplane_dref_index": 15, "touchosc_address": "/UNDEFINED"},
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA21",
        "xplane_dref_index": 16,
        "touchosc_address": "/label/ventilation_cab_fans",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA21",
        "xplane_dref_index": 17,
        "touchosc_address": "/label/ventilation_extract_lower",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA21",
        "xplane_dref_index": 18,
        "touchosc_address": "/label/ventilation_extract_upper",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA21",
        "xplane_dref_index": 19,
        "touchosc_address": "/label/ventilation_blower_lower",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA21",
        "xplane_dref_index": 20,
        "touchosc_address": "/label/ventilation_blower_upper",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA21",
        "xplane_dref_index": 21,
        "touchosc_address": "/label/fwd_isol_valve_lower",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA21",
        "xplane_dref_index": 22,
        "touchosc_address": "/label/fwd_isol_valve_upper",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA21",
        "xplane_dref_index": 23,
        "touchosc_address": "/label/aft_isol_valve_lower",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA21",
        "xplane_dref_index": 24,
        "touchosc_address": "/label/aft_isol_valve_upper",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA21",
        "xplane_dref_index": 25,
        "touchosc_address": "/label/hot_air_lower",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA21",
        "xplane_dref_index": 26,
        "touchosc_address": "/label/hot_air_upper",
    },
    # AirbusFBW/OHPLightsATA24[64]
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA24",
        "xplane_dref_index": 0,
        "touchosc_address": "/label/elec_gen_1_lower",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA24",
        "xplane_dref_index": 1,
        "touchosc_address": "/label/elec_gen_1_upper",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA24",
        "xplane_dref_index": 2,
        "touchosc_address": "/label/elec_gen_2_lower",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA24",
        "xplane_dref_index": 3,
        "touchosc_address": "/label/elec_gen_2_upper",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA24",
        "xplane_dref_index": 4,
        "touchosc_address": "/label/elec_apu_gen_lower",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA24",
        "xplane_dref_index": 5,
        "touchosc_address": "/label/elec_apu_gen_upper",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA24",
        "xplane_dref_index": 6,
        "touchosc_address": "/label/elec_ext_pwr_lower",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA24",
        "xplane_dref_index": 7,
        "touchosc_address": "/label/elec_ext_pwr_upper",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA24",
        "xplane_dref_index": 8,
        "touchosc_address": "/label/elec_bus_tie",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA24",
        "xplane_dref_index": 9,
        "touchosc_address": "/label/elec_bat_1_lower",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA24",
        "xplane_dref_index": 10,
        "touchosc_address": "/label/elec_bat_1_upper",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA24",
        "xplane_dref_index": 11,
        "touchosc_address": "/label/elec_bat_2_lower",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA24",
        "xplane_dref_index": 12,
        "touchosc_address": "/label/elec_bat_2_upper",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA24",
        "xplane_dref_index": 13,
        "touchosc_address": "/label/elec_ac_ess_feed_lower",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA24",
        "xplane_dref_index": 14,
        "touchosc_address": "/label/elec_ac_ess_feed_upper",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA24",
        "xplane_dref_index": 15,
        "touchosc_address": "/label/elec_commercial",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA24",
        "xplane_dref_index": 16,
        "touchosc_address": "/label/elec_galley_lower",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA24",
        "xplane_dref_index": 17,
        "touchosc_address": "/label/elec_galley_upper",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA24",
        "xplane_dref_index": 21,
        "touchosc_address": "/label/emer_elec_pwr_gen_1_line_lower",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA24",
        "xplane_dref_index": 22,
        "touchosc_address": "/label/emer_elec_pwr_gen_1_line_upper",
    },
    # AirbusFBW/OHPLightsATA26[64]
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA26",
        "xplane_dref_index": 0,
        "touchosc_address": "/label/fire_eng_1",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA26",
        "xplane_dref_index": 1,
        "touchosc_address": "/label/fire_eng_1_agent_1_lower",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA26",
        "xplane_dref_index": 2,
        "touchosc_address": "/label/fire_eng_1_agent_1_upper",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA26",
        "xplane_dref_index": 3,
        "touchosc_address": "/label/fire_eng_1_agent_2_lower",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA26",
        "xplane_dref_index": 4,
        "touchosc_address": "/label/fire_eng_1_agent_2_upper",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA26",
        "xplane_dref_index": 5,
        "touchosc_address": "/label/fire_eng_2",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA26",
        "xplane_dref_index": 6,
        "touchosc_address": "/label/fire_eng_2_agent_1_lower",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA26",
        "xplane_dref_index": 7,
        "touchosc_address": "/label/fire_eng_2_agent_1_upper",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA26",
        "xplane_dref_index": 8,
        "touchosc_address": "/label/fire_eng_2_agent_2_lower",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA26",
        "xplane_dref_index": 9,
        "touchosc_address": "/label/fire_eng_2_agent_2_lower",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA26",
        "xplane_dref_index": 22,
        "touchosc_address": "/label/fire_apu_agent_lower",
    },
    # AirbusFBW/OHPLightsATA27[64]
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA27",
        "xplane_dref_index": 0,
        "touchosc_address": "/label/flt_ctl_elac_1_lower",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA27",
        "xplane_dref_index": 1,
        "touchosc_address": "/label/flt_ctl_elac_1_upper",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA27",
        "xplane_dref_index": 2,
        "touchosc_address": "/label/flt_ctl_elac_2_lower",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA27",
        "xplane_dref_index": 3,
        "touchosc_address": "/label/flt_ctl_elac_2_upper",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA27",
        "xplane_dref_index": 4,
        "touchosc_address": "/label/flt_ctl_sec_1_lower",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA27",
        "xplane_dref_index": 5,
        "touchosc_address": "/label/flt_ctl_sec_1_upper",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA27",
        "xplane_dref_index": 6,
        "touchosc_address": "/label/flt_ctl_sec_2_lower",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA27",
        "xplane_dref_index": 7,
        "touchosc_address": "/label/flt_ctl_sec_2_upper",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA27",
        "xplane_dref_index": 8,
        "touchosc_address": "/label/flt_ctl_sec_3_lower",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA27",
        "xplane_dref_index": 9,
        "touchosc_address": "/label/flt_ctl_sec_3_upper",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA27",
        "xplane_dref_index": 10,
        "touchosc_address": "/label/flt_ctl_fac_1_lower",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA27",
        "xplane_dref_index": 11,
        "touchosc_address": "/label/flt_ctl_fac_1_upper",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA27",
        "xplane_dref_index": 12,
        "touchosc_address": "/label/flt_ctl_fac_2_lower",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA27",
        "xplane_dref_index": 13,
        "touchosc_address": "/label/flt_ctl_fac_2_upper",
    },
    # AirbusFBW/OHPLightsATA28[64]
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA28",
        "xplane_dref_index": 0,
        "touchosc_address": "/label/fuel_ltk_pumps_1_lower",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA28",
        "xplane_dref_index": 1,
        "touchosc_address": "/label/fuel_ltk_pumps_1_upper",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA28",
        "xplane_dref_index": 2,
        "touchosc_address": "/label/fuel_ltk_pumps_2_lower",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA28",
        "xplane_dref_index": 3,
        "touchosc_address": "/label/fuel_ltk_pumps_2_upper",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA28",
        "xplane_dref_index": 4,
        "touchosc_address": "/label/fuel_ctr_tk_1_lower",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA28",
        "xplane_dref_index": 5,
        "touchosc_address": "/label/fuel_ctr_tk_1_upper",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA28",
        "xplane_dref_index": 6,
        "touchosc_address": "/label/fuel_ctr_tk_2_lower",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA28",
        "xplane_dref_index": 7,
        "touchosc_address": "/label/fuel_ctr_tk_2_upper",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA28",
        "xplane_dref_index": 8,
        "touchosc_address": "/label/fuel_rtk_pumps_1_lower",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA28",
        "xplane_dref_index": 9,
        "touchosc_address": "/label/fuel_rtk_pumps_1_upper",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA28",
        "xplane_dref_index": 10,
        "touchosc_address": "/label/fuel_rtk_pumps_2_lower",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA28",
        "xplane_dref_index": 11,
        "touchosc_address": "/label/fuel_rtk_pumps_2_upper",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA28",
        "xplane_dref_index": 12,
        "touchosc_address": "/label/fuel_mode_sel_lower",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA28",
        "xplane_dref_index": 13,
        "touchosc_address": "/label/fuel_mode_sel_upper",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA28",
        "xplane_dref_index": 14,
        "touchosc_address": "/label/fuel_x_feed_lower",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA28",
        "xplane_dref_index": 15,
        "touchosc_address": "/label/fuel_x_feed_upper",
    },
    # AirbusFBW/OHPLightsATA29[64]
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA29",
        "xplane_dref_index": 0,
        "touchosc_address": "/label/hyd_eng_1_pump_lower",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA29",
        "xplane_dref_index": 1,
        "touchosc_address": "/label/hyd_eng_1_pump_upper",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA29",
        "xplane_dref_index": 2,
        "touchosc_address": "/label/hyd_eng_2_pump_lower",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA29",
        "xplane_dref_index": 3,
        "touchosc_address": "/label/hyd_eng_2_pump_upper",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA29",
        "xplane_dref_index": 4,
        "touchosc_address": "/label/hyd_blue_elec_pump_lower",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA29",
        "xplane_dref_index": 5,
        "touchosc_address": "/label/hyd_blue_elec_pump_upper",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA29",
        "xplane_dref_index": 6,
        "touchosc_address": "/label/hyd_yellow_elec_pump_lower",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA29",
        "xplane_dref_index": 7,
        "touchosc_address": "/label/hyd_yellow_elec_pump_upper",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA29",
        "xplane_dref_index": 8,
        "touchosc_address": "/label/hyd_ptu_lower",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA29",
        "xplane_dref_index": 9,
        "touchosc_address": "/label/hyd_ptu_upper",
    },
    # AirbusFBW/OHPLightsATA30[64]
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA30",
        "xplane_dref_index": 0,
        "touchosc_address": "/label/anti_ice_wing_lower",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA30",
        "xplane_dref_index": 1,
        "touchosc_address": "/label/anti_ice_wing_upper",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA30",
        "xplane_dref_index": 2,
        "touchosc_address": "/label/anti_ice_eng_1_lower",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA30",
        "xplane_dref_index": 3,
        "touchosc_address": "/label/anti_ice_eng_1_upper",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA30",
        "xplane_dref_index": 4,
        "touchosc_address": "/label/anti_ice_eng_2_lower",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA30",
        "xplane_dref_index": 5,
        "touchosc_address": "/label/anti_ice_eng_2_upper",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA30",
        "xplane_dref_index": 10,
        "touchosc_address": "/label/probe_window_heat",
    },
    # AirbusFBW/OHPLightsATA31[64] (also defined in main_panel_labels and pedestal_labels)
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA31",
        "xplane_dref_index": 10,
        "touchosc_address": "/label/evac_command_lower",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA31",
        "xplane_dref_index": 11,
        "touchosc_address": "/label/evac_command_upper",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA31",
        "xplane_dref_index": 12,
        "touchosc_address": "/label/emer_exit_lt",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA31",
        "xplane_dref_index": 13,
        "touchosc_address": "/label/calls_emer_lower",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA31",
        "xplane_dref_index": 14,
        "touchosc_address": "/label/calls_emer_upper",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA31",
        "xplane_dref_index": 15,
        "touchosc_address": "/label/rcdr_gnd_ctl",
    },
    # AirbusFBW/OHPLightsATA34[64] (also defined in main_panel_labels)
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA34",
        "xplane_dref_index": 0,
        "touchosc_address": "/label/adr1_lower",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA34",
        "xplane_dref_index": 1,
        "touchosc_address": "/label/adr1_upper",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA34",
        "xplane_dref_index": 2,
        "touchosc_address": "/label/adr2_lower",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA34",
        "xplane_dref_index": 3,
        "touchosc_address": "/label/adr2_upper",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA34",
        "xplane_dref_index": 4,
        "touchosc_address": "/label/adr3_lower",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA34",
        "xplane_dref_index": 5,
        "touchosc_address": "/label/adr3_upper",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA34",
        "xplane_dref_index": 6,
        "touchosc_address": "/label/adirs_ir1_lower",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA34",
        "xplane_dref_index": 7,
        "touchosc_address": "/label/adirs_ir1_upper",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA34",
        "xplane_dref_index": 8,
        "touchosc_address": "/label/adirs_ir2_lower",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA34",
        "xplane_dref_index": 9,
        "touchosc_address": "/label/adirs_ir2_upper",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA34",
        "xplane_dref_index": 10,
        "touchosc_address": "/label/adirs_ir3_lower",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA34",
        "xplane_dref_index": 11,
        "touchosc_address": "/label/adirs_ir3_upper",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA34",
        "xplane_dref_index": 12,
        "touchosc_address": "/label/adirs_battery",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA34",
        "xplane_dref_index": 13,
        "touchosc_address": "/label/gpws_sys_lower",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA34",
        "xplane_dref_index": 14,
        "touchosc_address": "/label/gpws_sys_upper",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA34",
        "xplane_dref_index": 15,
        "touchosc_address": "/label/gpws_g_s_mode",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA34",
        "xplane_dref_index": 16,
        "touchosc_address": "/label/gpws_flap_mode",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA34",
        "xplane_dref_index": 17,
        "touchosc_address": "/label/gpws_ldg_flap_3",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA34",
        "xplane_dref_index": 26,
        "touchosc_address": "/label/gpws_terr_lower",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA34",
        "xplane_dref_index": 27,
        "touchosc_address": "/label/gpws_terr_upper",
    },
    # AirbusFBW/OHPLightsATA35[64]
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA35",
        "xplane_dref_index": 1,
        "touchosc_address": "/label/crew_supply",
    },
    # AirbusFBW/OHPLightsATA49[64]
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA49",
        "xplane_dref_index": 0,
        "touchosc_address": "/label/apu_master_sw_lower",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA49",
        "xplane_dref_index": 1,
        "touchosc_address": "/label/apu_master_sw_upper",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA49",
        "xplane_dref_index": 2,
        "touchosc_address": "/label/apu_start_lower",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA49",
        "xplane_dref_index": 3,
        "touchosc_address": "/label/apu_start_upper",
    },
    # Add xplane_dref to this list
    # AirbusFBW/OHPLightsATA70[64]
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA70",
        "xplane_dref_index": 0,
        "touchosc_address": "/label/eng_man_start_1",
    },
    {
        "control_type": AirbusLabel,
        "xplane_dref_address": "AirbusFBW/OHPLightsATA70",
        "xplane_dref_index": 1,
        "touchosc_address": "/label/eng_man_start_2",
    },
    # AirbusFBW/BatVolts
    {
        "control_type": DynamicLabel,
        "xplane_dref_address": "AirbusFBW/BatVolts",
        "xplane_dref_index": 0,
        "touchosc_address": "/label/elec_battery_voltage_1",
    },
    {
        "control_type": DynamicLabel,
        "xplane_dref_address": "AirbusFBW/BatVolts",
        "xplane_dref_index": 1,
        "touchosc_address": "/label/elec_battery_voltage_2",
    },
]
